"""Testi fissi del sito in ogni lingua (l'italiano è la lingua principale, alla radice del sito).

Le traduzioni degli articoli stanno in content/i18n/<lingua>/<slug-italiano>.md
(front matter: title, description, slug, cover; poi il testo). Un articolo compare in una lingua
solo se esiste la sua traduzione. Le didascalie dei NUMERI stanno in content/i18n/<lingua>/_numeri.json
(dizionario "slug-italiano|numero" -> didascalia), le pagine (privacy) in content/i18n/<lingua>/pagine/.
"""

ORDINE = ["it", "en", "de", "fr", "es", "ru", "zh", "ar"]
# Lingue pubblicate davvero: si aggiunge una lingua qui solo quando TUTTE le sue traduzioni sono pronte e approvate.
ATTIVE = ["it"]

L = {
"it": dict(
    name="Italiano", short="IT", locale="it_IT", dir="ltr",
    tagline="Storie, territori e tecnica del vino",
    months=["gennaio","febbraio","marzo","aprile","maggio","giugno","luglio","agosto","settembre","ottobre","novembre","dicembre"],
    date="{d} {m} {y}",
    cat_dir="categoria",
    cats={"Vitigni": ("Vitigni", "Le uve e il loro carattere", "vitigni"),
          "Territori": ("Territori", "Dove nasce il vino", "territori"),
          "Tecnica": ("Tecnica", "Come si fa, davvero", "tecnica"),
          "Servizio": ("Servizio", "Bicchieri, gradi, decanter", "servizio"),
          "Guide": ("Guide", "Per orientarsi", "guide")},
    read_time="{n} minuti di lettura", long_read="Lettura lunga", minutes="{n} minuti",
    see_all="Vedi tutti ›", read="Leggi ›", n_articles="{n} articoli", in_cat="in",
    selection="Da bere e da sapere", selection_sub="Una selezione dall'archivio di Vinofilo",
    numbers="I numeri", numbers_sub="Cifre da raccontare a cena",
    latest="Ultimi articoli", latest_sub="Appena usciti dalla cantina",
    explore="Esplora per tema", explore_sub="L'archivio di Vinofilo in cinque capitoli",
    more="Da leggere ancora", coming="Articoli in arrivo.",
    privacy="Privacy e cookie", cookie_prefs="Preferenze cookie",
    home_desc="Vinofilo: storie, territori e tecnica del vino. Vitigni, territori, tecnica e servizio raccontati con un punto di vista.",
    cat_desc="{cat} — {desc}. Gli articoli di Vinofilo.",
    nf_title="Pagina non trovata", nf_big="13,5°", nf_h1="Mi sa che ti sei perso", nf_text="Questa pagina non esiste.", nf_back="Torna alla home ›",
    languages="Lingua",
    banner="Usiamo cookie di statistica (Google Analytics) per capire quali articoli vengono letti. Si attivano solo se accetti.",
    accept="Accetta", reject="Rifiuta",
),
"en": dict(
    name="English", short="EN", locale="en_US", dir="ltr",
    tagline="Stories, places and craft of wine",
    months=["January","February","March","April","May","June","July","August","September","October","November","December"],
    date="{d} {m} {y}",
    cat_dir="category",
    cats={"Vitigni": ("Grapes", "Varieties and their character", "grapes"),
          "Territori": ("Regions", "Where wine is born", "regions"),
          "Tecnica": ("Craft", "How it is really made", "craft"),
          "Servizio": ("Serving", "Glasses, temperatures, decanters", "serving"),
          "Guide": ("Guides", "To find your way", "guides")},
    read_time="{n} min read", long_read="Long read", minutes="{n} minutes",
    see_all="See all ›", read="Read ›", n_articles="{n} articles", in_cat="in",
    selection="To drink and to know", selection_sub="A selection from the Vinofilo archive",
    numbers="The numbers", numbers_sub="Four figures from our articles, different every time",
    latest="Latest articles", latest_sub="Fresh from the cellar",
    explore="Explore by theme", explore_sub="The Vinofilo archive in five chapters",
    more="Read next", coming="Articles coming soon.",
    privacy="Privacy and cookies", cookie_prefs="Cookie preferences",
    home_desc="Vinofilo: stories, places and craft of Italian wine. Grapes, regions, winemaking and serving, told with a point of view.",
    cat_desc="{cat} — {desc}. Articles from Vinofilo.",
    nf_title="Page not found", nf_h1="Empty bottle", nf_text="This page does not exist.", nf_back="Back to the home page ›",
    languages="Language",
    banner="We use statistics cookies (Google Analytics) to understand which articles are read. They are only enabled if you accept.",
    accept="Accept", reject="Decline",
),
"de": dict(
    name="Deutsch", short="DE", locale="de_DE", dir="ltr",
    tagline="Geschichten, Regionen und Handwerk des Weins",
    months=["Januar","Februar","März","April","Mai","Juni","Juli","August","September","Oktober","November","Dezember"],
    date="{d}. {m} {y}",
    cat_dir="kategorie",
    cats={"Vitigni": ("Rebsorten", "Trauben und ihr Charakter", "rebsorten"),
          "Territori": ("Regionen", "Wo der Wein entsteht", "regionen"),
          "Tecnica": ("Handwerk", "Wie er wirklich gemacht wird", "handwerk"),
          "Servizio": ("Service", "Gläser, Temperaturen, Dekanter", "service"),
          "Guide": ("Ratgeber", "Zur Orientierung", "ratgeber")},
    read_time="{n} Min. Lesezeit", long_read="Lange Lektüre", minutes="{n} Minuten",
    see_all="Alle ansehen ›", read="Lesen ›", n_articles="{n} Artikel", in_cat="in",
    selection="Zum Trinken und Wissen", selection_sub="Eine Auswahl aus dem Vinofilo-Archiv",
    numbers="Die Zahlen", numbers_sub="Vier Zahlen aus unseren Artikeln, jedes Mal andere",
    latest="Neueste Artikel", latest_sub="Frisch aus dem Keller",
    explore="Nach Themen entdecken", explore_sub="Das Vinofilo-Archiv in fünf Kapiteln",
    more="Weiterlesen", coming="Artikel folgen in Kürze.",
    privacy="Datenschutz und Cookies", cookie_prefs="Cookie-Einstellungen",
    home_desc="Vinofilo: Geschichten, Regionen und Handwerk des italienischen Weins. Rebsorten, Regionen, Weinbereitung und Service – mit klarer Haltung erzählt.",
    cat_desc="{cat} — {desc}. Artikel von Vinofilo.",
    nf_title="Seite nicht gefunden", nf_h1="Leere Flasche", nf_text="Diese Seite gibt es nicht.", nf_back="Zur Startseite ›",
    languages="Sprache",
    banner="Wir verwenden Statistik-Cookies (Google Analytics), um zu verstehen, welche Artikel gelesen werden. Sie werden nur aktiviert, wenn Sie zustimmen.",
    accept="Zustimmen", reject="Ablehnen",
),
"fr": dict(
    name="Français", short="FR", locale="fr_FR", dir="ltr",
    tagline="Histoires, terroirs et savoir-faire du vin",
    months=["janvier","février","mars","avril","mai","juin","juillet","août","septembre","octobre","novembre","décembre"],
    date="{d} {m} {y}",
    cat_dir="categorie",
    cats={"Vitigni": ("Cépages", "Les raisins et leur caractère", "cepages"),
          "Territori": ("Terroirs", "Là où naît le vin", "terroirs"),
          "Tecnica": ("Technique", "Comment on le fait, vraiment", "technique"),
          "Servizio": ("Service", "Verres, températures, carafes", "service"),
          "Guide": ("Guides", "Pour s'y retrouver", "guides")},
    read_time="{n} min de lecture", long_read="Lecture longue", minutes="{n} minutes",
    see_all="Tout voir ›", read="Lire ›", n_articles="{n} articles", in_cat="dans",
    selection="À boire et à savoir", selection_sub="Une sélection des archives de Vinofilo",
    numbers="Les chiffres", numbers_sub="Quatre chiffres tirés de nos articles, différents à chaque fois",
    latest="Derniers articles", latest_sub="Tout juste sortis de la cave",
    explore="Explorer par thème", explore_sub="Les archives de Vinofilo en cinq chapitres",
    more="À lire aussi", coming="Articles à venir.",
    privacy="Confidentialité et cookies", cookie_prefs="Préférences cookies",
    home_desc="Vinofilo : histoires, terroirs et savoir-faire du vin italien. Cépages, régions, vinification et service, racontés avec un point de vue.",
    cat_desc="{cat} — {desc}. Les articles de Vinofilo.",
    nf_title="Page introuvable", nf_h1="Bouteille vide", nf_text="Cette page n'existe pas.", nf_back="Retour à l'accueil ›",
    languages="Langue",
    banner="Nous utilisons des cookies statistiques (Google Analytics) pour savoir quels articles sont lus. Ils ne s'activent que si vous acceptez.",
    accept="Accepter", reject="Refuser",
),
"es": dict(
    name="Español", short="ES", locale="es_ES", dir="ltr",
    tagline="Historias, territorios y oficio del vino",
    months=["enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre"],
    date="{d} de {m} de {y}",
    cat_dir="categoria",
    cats={"Vitigni": ("Variedades", "Las uvas y su carácter", "variedades"),
          "Territori": ("Territorios", "Donde nace el vino", "territorios"),
          "Tecnica": ("Técnica", "Cómo se hace de verdad", "tecnica"),
          "Servizio": ("Servicio", "Copas, temperaturas, decantadores", "servicio"),
          "Guide": ("Guías", "Para orientarse", "guias")},
    read_time="{n} min de lectura", long_read="Lectura larga", minutes="{n} minutos",
    see_all="Ver todos ›", read="Leer ›", n_articles="{n} artículos", in_cat="en",
    selection="Para beber y saber", selection_sub="Una selección del archivo de Vinofilo",
    numbers="Las cifras", numbers_sub="Cuatro cifras de nuestros artículos, distintas cada vez",
    latest="Últimos artículos", latest_sub="Recién salidos de la bodega",
    explore="Explorar por tema", explore_sub="El archivo de Vinofilo en cinco capítulos",
    more="Sigue leyendo", coming="Próximamente, nuevos artículos.",
    privacy="Privacidad y cookies", cookie_prefs="Preferencias de cookies",
    home_desc="Vinofilo: historias, territorios y oficio del vino italiano. Variedades, regiones, elaboración y servicio, contados con un punto de vista.",
    cat_desc="{cat} — {desc}. Los artículos de Vinofilo.",
    nf_title="Página no encontrada", nf_h1="Botella vacía", nf_text="Esta página no existe.", nf_back="Volver al inicio ›",
    languages="Idioma",
    banner="Usamos cookies de estadística (Google Analytics) para saber qué artículos se leen. Solo se activan si aceptas.",
    accept="Aceptar", reject="Rechazar",
),
"ru": dict(
    name="Русский", short="RU", locale="ru_RU", dir="ltr",
    tagline="Истории, регионы и ремесло вина",
    months=["января","февраля","марта","апреля","мая","июня","июля","августа","сентября","октября","ноября","декабря"],
    date="{d} {m} {y}",
    cat_dir="rubriki",
    cats={"Vitigni": ("Сорта", "Виноград и его характер", "sorta"),
          "Territori": ("Регионы", "Где рождается вино", "regiony"),
          "Tecnica": ("Технология", "Как его делают на самом деле", "tekhnologiya"),
          "Servizio": ("Подача", "Бокалы, температура, декантеры", "podacha"),
          "Guide": ("Путеводители", "Чтобы не потеряться", "putevoditeli")},
    read_time="{n} мин чтения", long_read="Большой материал", minutes="{n} мин",
    see_all="Все материалы ›", read="Читать ›", n_articles="Статей: {n}", in_cat="в рубрике",
    selection="Пить и знать", selection_sub="Подборка из архива Vinofilo",
    numbers="Цифры", numbers_sub="Четыре цифры из наших статей, каждый раз другие",
    latest="Новые статьи", latest_sub="Только что из погреба",
    explore="Темы", explore_sub="Архив Vinofilo в пяти главах",
    more="Читайте также", coming="Скоро здесь появятся статьи.",
    privacy="Конфиденциальность и cookie", cookie_prefs="Настройки cookie",
    home_desc="Vinofilo: истории, регионы и ремесло итальянского вина. Сорта, регионы, виноделие и подача — с собственной точкой зрения.",
    cat_desc="{cat} — {desc}. Статьи Vinofilo.",
    nf_title="Страница не найдена", nf_h1="Пустая бутылка", nf_text="Такой страницы нет.", nf_back="На главную ›",
    languages="Язык",
    banner="Мы используем статистические cookie (Google Analytics), чтобы понимать, какие статьи читают. Они включаются только с вашего согласия.",
    accept="Принять", reject="Отклонить",
),
"zh": dict(
    name="中文", short="中文", locale="zh_CN", dir="ltr",
    tagline="葡萄酒的故事、产区与工艺",
    months=[str(i) for i in range(1, 13)],
    date="{y}年{m}月{d}日",
    cat_dir="fenlei",
    cats={"Vitigni": ("葡萄品种", "葡萄与它们的个性", "pinzhong"),
          "Territori": ("产区", "葡萄酒诞生的地方", "chanqu"),
          "Tecnica": ("工艺", "葡萄酒究竟如何酿成", "gongyi"),
          "Servizio": ("侍酒", "酒杯、温度与醒酒器", "shijiu"),
          "Guide": ("指南", "帮你找到方向", "zhinan")},
    read_time="阅读约{n}分钟", long_read="长篇阅读", minutes="{n}分钟",
    see_all="查看全部 ›", read="阅读 ›", n_articles="{n}篇文章", in_cat="栏目：",
    selection="品饮与知识", selection_sub="精选自 Vinofilo 文章库",
    numbers="数字", numbers_sub="来自文章的四个数字，每次都不同",
    latest="最新文章", latest_sub="刚从酒窖出炉",
    explore="按主题浏览", explore_sub="Vinofilo 文章库的五个篇章",
    more="延伸阅读", coming="文章即将上线。",
    privacy="隐私与 Cookie", cookie_prefs="Cookie 设置",
    home_desc="Vinofilo：意大利葡萄酒的故事、产区与工艺。品种、产区、酿造与侍酒，有观点地讲述。",
    cat_desc="{cat}——{desc}。Vinofilo 的文章。",
    nf_title="页面不存在", nf_h1="空瓶", nf_text="此页面不存在。", nf_back="返回首页 ›",
    languages="语言",
    banner="我们使用统计 Cookie（Google Analytics）来了解哪些文章被阅读。只有在您同意后才会启用。",
    accept="同意", reject="拒绝",
),
"ar": dict(
    name="العربية", short="عربي", locale="ar_AR", dir="rtl",
    tagline="حكايات النبيذ ومناطقه وصنعته",
    months=["يناير","فبراير","مارس","أبريل","مايو","يونيو","يوليو","أغسطس","سبتمبر","أكتوبر","نوفمبر","ديسمبر"],
    date="{d} {m} {y}",
    cat_dir="aqsam",
    cats={"Vitigni": ("أصناف العنب", "العنب وطباعه", "asnaf"),
          "Territori": ("المناطق", "حيث يولد النبيذ", "manatiq"),
          "Tecnica": ("الصنعة", "كيف يُصنع حقًا", "sanaa"),
          "Servizio": ("التقديم", "الكؤوس والحرارة والدوارق", "taqdim"),
          "Guide": ("أدلة", "لتجد طريقك", "adilla")},
    read_time="قراءة {n} دقائق", long_read="قراءة مطوّلة", minutes="{n} دقائق",
    see_all="عرض الكل ‹", read="اقرأ ‹", n_articles="{n} مقالات", in_cat="في",
    selection="للشرب وللمعرفة", selection_sub="مختارات من أرشيف Vinofilo",
    numbers="بالأرقام", numbers_sub="أربعة أرقام من مقالاتنا، مختلفة في كل مرة",
    latest="أحدث المقالات", latest_sub="خرجت للتو من القبو",
    explore="تصفّح حسب الموضوع", explore_sub="أرشيف Vinofilo في خمسة فصول",
    more="اقرأ أيضًا", coming="مقالات قريبًا.",
    privacy="الخصوصية وملفات تعريف الارتباط", cookie_prefs="إعدادات ملفات تعريف الارتباط",
    home_desc="Vinofilo: حكايات النبيذ الإيطالي ومناطقه وصنعته. أصناف العنب والمناطق والصناعة والتقديم، برؤية خاصة.",
    cat_desc="{cat} — {desc}. مقالات Vinofilo.",
    nf_title="الصفحة غير موجودة", nf_h1="زجاجة فارغة", nf_text="هذه الصفحة غير موجودة.", nf_back="العودة إلى الرئيسية ‹",
    languages="اللغة",
    banner="نستخدم ملفات تعريف ارتباط إحصائية (Google Analytics) لمعرفة المقالات التي تُقرأ. لا تُفعَّل إلا بموافقتك.",
    accept="موافقة", reject="رفض",
),
}


def fmt_date(lang, d):
    t = L[lang]
    return t["date"].format(d=d.day, m=t["months"][d.month - 1], y=d.year)


def prefix(lang):
    return "" if lang == "it" else f"/{lang}"
